name: Set Environment Variables

on:
  workflow_call:

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Set DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV